/** Generated by scripts/build.ts from the prebuilt browser assets. */
declare module 'virtual:tipprunde-assets' {
  const manifest: import('./manifest-assets.ts').AssetManifest
  export default manifest
}
